from snakemake.utils import validate
from snakemake.utils import min_version

min_version("7.0.0")

configfile: "config/analysis.yaml"

validate(config, schema="config/schema/config.schema.yaml")

include: "rules/01_hub.smk"

rule all:
    input:
        os.path.join(config["analysis_name"]+os.sep+config['folder_out'], 'directory.txt'),