###################################################################################################################
############################################### User defined params ###############################################
###################################################################################################################

### analysis_name: your analysis must have a unique name. This name will be both the name of your configuration file, and the name of the folder with all analysis
analysis_name: "analysis"

### fastq_home_dir: specify the directory containing the original fastq files, concatenate lanes
fastq_home_dir: "<path-to-fastq-files-directory>"

### single_paired_end: specify if reads are single or paired end ('single' or 'paired')
single_paired_end: "paired"

### concatenate_fastq: specify if you want to concatenate the reads ('True' or 'False')
concatenate_fastq: "False"

### cutadapters_bool: specify if you want to trim the reads ('True' or 'False')
cutadapters_bool: "False"

### star_dir: specify directory where genome is located
star_dir: "/<path>/STAR"

### gtf_annotation: specify directory where gene annotation is located
gtf_annotation: "/<path>/refGene.gtf"

### genome_built_version: version of the built genome. It must be consistent with the aligner_dir chosen
genome_built_version: "mm39"

### merge_bams: specify if you want to merge the bam files (i.e., if you have many lanes) ('True' or 'False')
merge_bams: "False"

### bigDataUrl: specify the location for public bigWigs and this is the link you can copy and paste into UCSC
### NB: url must end with a slash ("/")
bigDataUrl: "https://<path>/"



###################################################################################################################
########################################## Copy/Move folders (Optional) ###########################################
###################################################################################################################

### move_output_files: specify if you want to move the output files ('True' or 'False')
move_output_files: "False"
### Specify the directory where final files must be moved.
output_dir:        "<path-to-output-directory>"
### Specify tag output directory.
tag_output_dir:    "<tag-output-directory>"

###################################################################################################################

### move_bw_public_folder: specify if you want to move the output files in a public folder ('True' or 'False'). 
### This is required for visulaisation on the UCSC genome browser
move_bw_public_folder: "False"
### Specify public directory where bw files must be copied.
public_output_dir:     "<path-to-output-directory>"
### Specify tag public output directory.
tag_public_output_dir: "<tag-output-directory>"


###################################################################################################################
######################################### Optional rule params (Optional) #########################################
###################################################################################################################

### Option to modify cutadapt parameters (see trimmomatic user manual)
trimming_SE_extra:          "ILLUMINACLIP:adapters/SE.fa:2:40:15 SLIDINGWINDOW:4:20" # if single_paired_end == 'single'
trimming_PE_extra:          "ILLUMINACLIP:adapters/PE.fa:2:40:15 SLIDINGWINDOW:4:20" # if single_paired_end == 'paired'

### Option to modify samtools_sort parameters
samtools_sort_extra:        "-m 4G"

### Option to modify mark_duplicates parameters
mark_duplicates_extra:      "--REMOVE_DUPLICATES False"

### Option to modify samtools_index parameters
samtools_index_extra:        ""

### bam_coverage_paramsX: option to modify bam_covarage parameters (default for Lanceotron)
bam_coverage_params1:        "-bs 1 --normalizeUsing RPKM"
bam_coverage_params2:        "--extendReads"



###################################################################################################################
############################################ Clean folders (Optional) #############################################
###################################################################################################################

### delete_intermediate_files: specify if you want to delete intermediate files ('True' or 'False')
delete_intermediate_files: "False"

### Specify what output must be removed before moving output files ('False' = keep, 'True' = remove)
single_paired_folder_rm: "False"
reads_rm:                "True"
trimming_rm:             "True"
star_rm:                 "True"
sorted_rm:               "True"
merge_rm:                "True"
duplicates_rm:           "True"
indices_rm:              "False"
bam_coverage_rm:         "False"
feature_counts_rm:       "False"
track_rm:                "False"



###################################################################################################################
############################################## Folders (DO NOT touch) #############################################
###################################################################################################################

tmp:                  "results/tmp"

single_paired_folder: "results/00_fastq_home_dir"

reads:                "results/01_reads/01_original"
reads_qc:             "QCs/01_reads/01_original"

reads_concat:         "results/01_reads/02_concatenate"
reads_concat_qc:      "QCs/01_reads/02_concatenate"

trimming:             "results/02_trimming"
trimming_qc:          "QCs/02_trimming"

star:                 "results/03_star"
star_qc:              "QCs/03_star"

sorted:               "results/04_sorted"

merge:                "results/05_merge"
merge_qc:             "QCs/05_merge"

duplicates:           "results/06_duplicates"
duplicates_qc:        "QCs/06_duplicates"

indices:              "results/07_indices"

bam_coverage:         "results/08_bam_coverages"

feature_counts:       "results/09_feature_counts"

track:                "results/10_track"

cleaning:             "results/"
