###################################################################################################################
############################################### User defined params ###############################################
###################################################################################################################


### analysis_name: your analysis must have a unique name. This name will be both the name of your configuration file, and the name of the folder with all analysis
analysis_name: "analysis"

### genome: choose the genome for the UCSC track
genome: "" #<genome version> e.g., "hg38"



###################################################################################################################
################################################### Move folders ##################################################
###################################################################################################################

### Specify public directory where bw files must be copied (do not include final slash '/' at the end of the path)
pub_directory:     "" #<path-to-output-directory>
### Specify name of new directory that will be created in the ouput directory
tag_pub_directory: "" #<tag-output-directory>



###################################################################################################################
############################################## Folders (DO NOT touch) #############################################
###################################################################################################################

folder_out:        "results/"