configfile: "config/analysis.yaml"

include: "rules/01_genome.smk"

rule all:
    input:
        ### download and index a reference genome
        os.path.join(config["analysis_name"]+os.sep+config['folder_out'], 'genome.txt'),